### ISSUE TITLE
Improve the setup instructions 

### ISSUE THREAD

**Issue by heaven00** [cbgaindia/union-budget-board#12]
#10

**Comment by heaven00** [comment]
@akshay2905  We don't need the *prequisites* etc headings, we can just have *setup* and three steps so far mentioned in #10 

The `requirements.txt` already contains all the requirements already including django-cms and all is modules that are being used or were added.

**Comment by imakshayverma** [comment]
I Agree. I failed to notice that, a requirement.txt is created in the setup. This makes it much simpler. Would write concise steps.

**Comment by heaven00** [comment]
#14
