### ISSUE TITLE
Should we have superset fork as a submodule here ?

### ISSUE THREAD

**Issue by heaven00** [cbgaindia/union-budget-board#2]

**Comment by heaven00** [comment]
Since the purpose of the superset is to assist budget board and all its configuration etc will be for that purpose alone I feel it should be added as a submodule here 

[submodules??](https://github.com/blog/2104-working-with-submodules)

**Comment by imakshayverma** [comment]
In my opinion, that would not be a great idea. Submodule's purpose is a little different. There won't be any code dependency between budget boards(cms instance) and superset instance. Second important point - We would just need one instance superset, whereas there would be different instances of budget boards which would be specific to union/states/municipal. Also distributed code management will be always simpler.

**Comment by heaven00** [comment]
Superset would be forked as a separate repo.

**Comment by imakshayverma** [comment]
Superset would be forked as a separate repo.
