### ISSUE TITLE
Extra space on homepage when using chrome-based browsers

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/union-budget-board#28]
Check the images below. 

**1. Chrome based browser** (on windows laptop and android tablet)

![image](https://user-images.githubusercontent.com/64309749/120621353-6d609600-c47b-11eb-8a81-e44a2571fe01.png)

**2. Firefox** (on windows laptop and android tablet)

![image](https://user-images.githubusercontent.com/64309749/120621399-781b2b00-c47b-11eb-9304-09e646545547.png)

The issue is  **not** present when viewing it on Webkit based browsers on iOS devices. 

@PixeledCode

**Comment by PixeledCode** [comment]
Issue fixed. Will be deployed and closed on Wednesday 14-jun-21

**Comment by PixeledCode** [comment]
deployed
