### ISSUE TITLE
How should we integrate superset with django CMS

### ISSUE THREAD

**Issue by heaven00** [cbgaindia/union-budget-board#7]

**Comment by heaven00** [comment]
@gggodhwani

**Comment by heaven00** [comment]
@akshay2905 okay so I have cms running on my system, do we have superset samples or something based on the way you are already using ?

**Comment by imakshayverma** [comment]
The superset samples can be taken from the instance we have and embed them as an iframe in the cms. That embedded iframe code would be part of the content on the cms.

**Comment by heaven00** [comment]
I was able to embed the complete dashboard using the following code 
```html
<iframe
  width="1600"
  height="1600"
  seamless
  frameBorder="0"
  scrolling="yes"
  src="http://52.214.125.248:8088/superset/dashboard/8/?preselect_filters=%7B%2252%22%3A%7B%22source%22%3A%5B%22Police.csv%22%5D%2C%22particulars_1%22%3A%5B%22Establishment%20Expenditure%20of%20the%20Centre%22%5D%2C%22particulars_2%22%3A%5B%22Central%20Armed%20Police%20Forces%22%5D%7D%7D&standalone=true&height=1600"
>
</iframe>
```
![firefox_screenshot_2018-01-19t12-00-42 854z](https://user-images.githubusercontent.com/1822197/35150050-b29f4cc8-fd3e-11e7-9b15-209369aea6d6.png)

**Tip** from here https://github.com/apache/incubator-superset/issues/1170

**Comment by heaven00** [comment]
the speed would be a concern though, we will have to optimize on our views, but @akshay2905 your thoughts ?

**Comment by gggodhwani** [comment]
I guess setting up Redis as cache may optimize speed a lot plus configuring Gunicorn server is something we need to explore.

**Comment by heaven00** [comment]
It loaded pretty fast after caching. Also we can design our views/dashboard in a manner that it doesn't have that much data transfer.

The question is of design simplification required for our user Base and making it usable

**Comment by imakshayverma** [comment]
The performance issue, I believe can be solved by Gaurav's proposal, also as he had mentioned, it is running on a development server. 

Would do a check of how data can be managed at front-end, to make sure we minimise queries. Also, a single page won't have many visualizations, we might need to test the turn-around time while we are surfing multiple pages.
